name: CI Pipeline
on: [push, pull_request]
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Instalar dependências
        run: npm install
      # - name: Rodar lint
      #   run: npm run lint
      #   working-directory: ./projeto-bookshelf
      - name: Build da aplicação 
        run: npm run build
      - name: Testar start da aplicação 
        run: |
          timeout 10 npm start &
          sleep 5
          kill %1 || true
      - name: Listagem de arquivos
        run: ls ${{ github.workspace }}
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push da imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/app-library:latest
      - name: Rodar Prisma Migrations
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: Popular Banco (Seed)
        run: npx prisma db seed
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }} 
      - name: Deploy com Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'